INSERT INTO users (login, password, first_name, last_name, email, role) VALUES
('admin', 'admin123', 'Alice', 'Admin', 'alice.admin@example.com', 'ADMINISTRATOR'),
('tracker1', 'tracker123', 'Tom', 'Tracker', 'tom.tracker@example.com', 'TRACKER'),
('tracker2', 'tracker123', 'Tracy', 'Lead', 'tracy.lead@example.com', 'TRACKER'),
('worker1', 'worker123', 'Will', 'One', 'will.one@example.com', 'WORKER'),
('worker2', 'worker123', 'Wendy', 'Two', 'wendy.two@example.com', 'WORKER'),
('worker3', 'worker123', 'Bob', 'Builder', 'bob.builder@example.com', 'WORKER'),
('worker4', 'worker123', 'Eve', 'Worker', 'eve.worker@example.com', 'WORKER'),
('guest1', 'guest123', 'Gary', 'Guest', 'gary.guest@example.com', 'GUEST'),
('guest2', 'guest123', 'Gina', 'Guest', 'gina.guest@example.com', 'GUEST'),
('worker5', 'worker123', 'Nina', 'Dev', 'nina.dev@example.com', 'WORKER');

INSERT INTO projects (name, description, code, owner_id, active) VALUES
('Core API', 'Main backend API development', 'PROJ-1', 2, TRUE),
('Mobile App', 'Android and iOS app', 'PROJ-2', 3, TRUE),
('Web Portal', 'Frontend dashboard', 'PROJ-3', 2, TRUE),
('Infrastructure', 'CI/CD and deployment', 'PROJ-4', 1, TRUE),
('Monitoring', 'Observability and alerting', 'PROJ-5', 1, TRUE),
('Billing', 'Payment and invoices', 'PROJ-6', 3, FALSE),
('Notifications', 'Email/SMS notifications', 'PROJ-7', 2, TRUE),
('Auth Service', 'Authentication and authorization', 'PROJ-8', 1, TRUE),
('Data Warehouse', 'Analytics pipeline', 'PROJ-9', 3, FALSE),
('Internal Tools', 'Admin/internal features', 'PROJ-10', 1, TRUE);

INSERT INTO tasks (code, title, description, project_id, assignee_id, reporter_id, status, created_at, updated_at) VALUES
('PROJ-1-TASK-1', 'Create users endpoint', 'Implement CRUD users', 1, 4, 2, 'NEW', NOW(), NOW()),
('PROJ-1-TASK-2', 'Implement auth', 'JWT login flow', 1, 5, 2, 'IN_PROGRESS', NOW(), NOW()),
('PROJ-1-TASK-3', 'Add validation', 'Input checks for DTOs', 1, 6, 2, 'REVIEW', NOW(), NOW()),
('PROJ-2-TASK-1', 'Setup mobile CI', 'GitHub actions for mobile', 2, 7, 3, 'DONE', NOW(), NOW()),
('PROJ-2-TASK-2', 'Push notifications', 'Implement push delivery', 2, 4, 3, 'IN_PROGRESS', NOW(), NOW()),
('PROJ-2-TASK-3', 'Fix crash in login', 'Null pointer in auth screen', 2, 5, 3, 'NEW', NOW(), NOW()),
('PROJ-3-TASK-1', 'Design dashboard', 'Project overview widgets', 3, 6, 2, 'REVIEW', NOW(), NOW()),
('PROJ-3-TASK-2', 'Task table sorting', 'Sort by status/date', 3, 7, 2, 'DONE', NOW(), NOW()),
('PROJ-3-TASK-3', 'User search UI', 'Filters by first/last name', 3, 4, 2, 'NEW', NOW(), NOW()),
('PROJ-4-TASK-1', 'Dockerize API', 'Create Dockerfile and compose', 4, 5, 1, 'DONE', NOW(), NOW()),
('PROJ-4-TASK-2', 'Add staging env', 'Separate stage config', 4, 6, 1, 'IN_PROGRESS', NOW(), NOW()),
('PROJ-4-TASK-3', 'Backup database', 'Nightly pg_dump backup', 4, 7, 1, 'REVIEW', NOW(), NOW()),
('PROJ-5-TASK-1', 'Setup Prometheus', 'Collect app metrics', 5, 4, 1, 'NEW', NOW(), NOW()),
('PROJ-5-TASK-2', 'Grafana dashboard', 'Visualize API health', 5, 5, 1, 'IN_PROGRESS', NOW(), NOW()),
('PROJ-5-TASK-3', 'Alert rules', 'Pager alerts for downtime', 5, 6, 1, 'CANCELLED', NOW(), NOW()),
('PROJ-6-TASK-1', 'Invoice schema', 'Design invoice entities', 6, 7, 3, 'REVIEW', NOW(), NOW()),
('PROJ-6-TASK-2', 'Stripe webhook', 'Process payment events', 6, 4, 3, 'NEW', NOW(), NOW()),
('PROJ-6-TASK-3', 'Refund logic', 'Implement refunds flow', 6, 5, 3, 'IN_PROGRESS', NOW(), NOW()),
('PROJ-7-TASK-1', 'SMTP integration', 'Email provider setup', 7, 6, 2, 'DONE', NOW(), NOW()),
('PROJ-7-TASK-2', 'SMS provider', 'Twilio integration', 7, 7, 2, 'REVIEW', NOW(), NOW()),
('PROJ-7-TASK-3', 'Template engine', 'Email template rendering', 7, 4, 2, 'NEW', NOW(), NOW()),
('PROJ-8-TASK-1', 'Password hashing', 'Hash with bcrypt/argon2', 8, 5, 1, 'IN_PROGRESS', NOW(), NOW()),
('PROJ-8-TASK-2', 'Role middleware', 'Authorization matrix', 8, 6, 1, 'DONE', NOW(), NOW()),
('PROJ-8-TASK-3', 'Refresh tokens', 'Token rotation', 8, 7, 1, 'NEW', NOW(), NOW()),
('PROJ-9-TASK-1', 'ETL pipeline', 'Daily job for analytics', 9, 4, 3, 'CANCELLED', NOW(), NOW()),
('PROJ-9-TASK-2', 'Data model', 'Dimension and fact tables', 9, 5, 3, 'REVIEW', NOW(), NOW()),
('PROJ-9-TASK-3', 'Export reports', 'CSV/PDF report generation', 9, 6, 3, 'IN_PROGRESS', NOW(), NOW()),
('PROJ-10-TASK-1', 'Admin panel', 'Internal tools UI', 10, 7, 1, 'NEW', NOW(), NOW()),
('PROJ-10-TASK-2', 'Audit logs', 'Track admin actions', 10, 4, 1, 'DONE', NOW(), NOW()),
('PROJ-10-TASK-3', 'Feature flags', 'Runtime toggles', 10, 5, 1, 'REVIEW', NOW(), NOW());
